#!/usr/bin/env python3
"""Render and validate the Portable Agent Contract using only the stdlib."""

# This file is vendored into repositories with heterogeneous formatter settings.
# ruff: noqa: E501, I001
# fmt: off

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

VERSION = "1.0.0"
GENERATED = (
    f"<!-- Generated by Portable Agent Contract {VERSION}. "
    "Edit .agents/instructions/*.md. -->"
)
DEFAULT_CONTRACT = {
    "schema_version": 1,
    "standard_version": VERSION,
    "instructions": {
        "core": ".agents/instructions/core.md",
        "claude": ".agents/instructions/claude.md",
        "codex": ".agents/instructions/codex.md",
        "max_rendered_bytes": 24576,
        "max_rendered_lines": 200,
    },
    "skills": {
        "canonical": ".agents/skills",
        "claude_projection": ".claude/skills",
    },
    "roles": {
        "canonical": ".agents/roles",
        "claude_projection": ".claude/agents",
        "codex_projection": ".codex/agents",
    },
}
CAPTURE_SKILL = """---
name: capture-learning
description: Capture a confirmed, reusable development discovery after a correction, incident, or repeated workflow reveals knowledge that should survive the current agent session.
---

# Capture Durable Learning

Use this only for verified knowledge that will improve later work. Do not promote
speculation, transient task state, credentials, personal paths, or one-off details.

1. Search existing instructions, skills, ADRs, project docs, fix-pattern references,
   tests, and hooks for the same knowledge. Update the existing source instead of
   creating a parallel copy.
2. Classify the discovery:
   - Always needed in most sessions: concise shared instruction.
   - Repeatable procedure with a recognizable trigger: focused skill.
   - Architectural rationale or tradeoff: ADR or maintained project document.
   - Recurring defect shape: fix-pattern reference plus a regression test when useful.
   - Deterministic requirement: hook, linter, type check, or test.
   - Temporary or personal fact: provider-local memory only.
3. Keep startup instructions small. Link to detailed material or load it through a
   skill instead of adding long incident histories to the always-on context.
4. Run `python3 .agents/agentctl.py render .` and
   `python3 .agents/agentctl.py check .` when the Portable Agent Contract is present.
5. Report what was promoted, where it now lives, and what evidence made it durable.
"""
WORKFLOW = """name: Agent contract

on:
  pull_request:
    paths:
      - '.agents/**'
      - '.claude/**'
      - '.codex/**'
      - '.github/copilot-instructions.md'
      - 'AGENTS.md'
      - 'CLAUDE.md'
      - '.github/workflows/agent-contract.yml'
  push:
    branches: [main, master]
    paths:
      - '.agents/**'
      - '.claude/**'
      - '.codex/**'
      - '.github/copilot-instructions.md'
      - 'AGENTS.md'
      - 'CLAUDE.md'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 .agents/agentctl.py check .
"""


class ContractError(RuntimeError):
    """A contract cannot be rendered without losing or weakening information."""


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def load_contract(root: Path) -> dict:
    path = root / ".agents/contract.json"
    if not path.is_file():
        raise ContractError(f"missing {path.relative_to(root)}")
    data = json.loads(read_text(path))
    if data.get("schema_version") != 1:
        raise ContractError("unsupported contract schema_version")
    return data


def instruction_output(root: Path, contract: dict) -> tuple[str, str]:
    spec = contract["instructions"]
    core = read_text(root / spec["core"]).strip()
    claude_delta = read_text(root / spec["claude"]).strip()
    codex_delta = read_text(root / spec["codex"]).strip()
    agents = "\n\n".join(part for part in (GENERATED, core, codex_delta) if part) + "\n"
    imports = [f"@{spec['core']}"]
    if claude_delta:
        imports.append(f"@{spec['claude']}")
    claude = GENERATED + "\n\n" + "\n".join(imports) + "\n"
    return agents, claude


def copilot_output(root: Path, contract: dict) -> str | None:
    """Render Copilot guidance when a repository has a provider-specific delta."""
    delta_path = root / ".agents/instructions/copilot.md"
    if not delta_path.is_file():
        return None
    spec = contract["instructions"]
    core = read_text(root / spec["core"]).strip()
    delta = read_text(delta_path).strip()
    return "\n\n".join(part for part in (GENERATED, core, delta) if part) + "\n"


def parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    match = re.match(r"^---\n(.*?)\n---\n?", text, re.S)
    if not match:
        raise ContractError("missing YAML frontmatter")
    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if not line.strip() or line[0].isspace() or line.startswith("-"):
            continue
        key, sep, value = line.partition(":")
        if not sep or not re.fullmatch(r"[a-z][a-z0-9_-]*", key):
            raise ContractError(f"unsupported frontmatter line: {line!r}")
        scalar = value.strip()
        if len(scalar) >= 2 and scalar[0] == scalar[-1] == '"':
            try:
                scalar = json.loads(scalar)
            except json.JSONDecodeError:
                pass
        elif len(scalar) >= 2 and scalar[0] == scalar[-1] == "'":
            scalar = scalar[1:-1].replace("''", "'")
        fields[key] = scalar
    return fields, text[match.end() :]


def role_outputs(role_dir: Path) -> tuple[str, str, str]:
    meta = json.loads(read_text(role_dir / "role.json"))
    name = meta["name"]
    description = meta["description"]
    body = read_text(role_dir / meta.get("instructions", "instructions.md")).strip()
    claude = meta.get("claude", {})
    lines = ["---", f"name: {name}", f"description: {description}"]
    if claude.get("tools"):
        lines.append("tools: " + ", ".join(claude["tools"]))
    if claude.get("model"):
        lines.append(f"model: {claude['model']}")
    lines += ["---", "", body, ""]
    codex = meta.get("codex", {})
    toml = [f"name = {json.dumps(name)}", f"description = {json.dumps(description)}"]
    for key in ("model", "model_reasoning_effort", "sandbox_mode"):
        if codex.get(key):
            toml.append(f"{key} = {json.dumps(codex[key])}")
    toml.append(f"developer_instructions = {json.dumps(body)}")
    return name, "\n".join(lines), "\n".join(toml) + "\n"


def tree_hash(path: Path) -> str:
    digest = hashlib.sha256()
    for item in sorted(p for p in path.rglob("*") if p.is_file()):
        digest.update(str(item.relative_to(path)).encode())
        digest.update(item.read_bytes())
    return digest.hexdigest()


def sync_skill_links(root: Path, contract: dict, *, fix: bool) -> list[str]:
    errors: list[str] = []
    canonical = root / contract["skills"]["canonical"]
    projection = root / contract["skills"]["claude_projection"]
    if not canonical.exists():
        return errors
    if fix:
        projection.mkdir(parents=True, exist_ok=True)
    for skill in sorted(
        p for p in canonical.iterdir() if p.is_dir() and (p / "SKILL.md").is_file()
    ):
        link = projection / skill.name
        relative = os.path.relpath(skill, projection)
        if link.is_symlink() and os.readlink(link) == relative:
            continue
        if link.exists() and link.is_dir() and not link.is_symlink():
            if tree_hash(link) == tree_hash(skill):
                continue
            errors.append(f"{link.relative_to(root)} diverges from canonical skill")
            continue
        if fix:
            if link.is_symlink() or link.exists():
                link.unlink()
            link.symlink_to(relative, target_is_directory=True)
        else:
            errors.append(f"missing skill projection {link.relative_to(root)}")
    return errors


def render(root: Path) -> None:
    contract = load_contract(root)
    agents, claude = instruction_output(root, contract)
    write_text(root / "AGENTS.md", agents)
    write_text(root / "CLAUDE.md", claude)
    copilot = copilot_output(root, contract)
    if copilot is not None:
        write_text(root / ".github/copilot-instructions.md", copilot)
    errors = sync_skill_links(root, contract, fix=True)
    if errors:
        raise ContractError("\n".join(errors))
    roles_root = root / contract["roles"]["canonical"]
    claude_roles = root / contract["roles"]["claude_projection"]
    codex_roles = root / contract["roles"]["codex_projection"]
    if roles_root.exists():
        claude_roles.mkdir(parents=True, exist_ok=True)
        codex_roles.mkdir(parents=True, exist_ok=True)
        for role_dir in sorted(p for p in roles_root.iterdir() if p.is_dir()):
            name, claude_text, codex_text = role_outputs(role_dir)
            write_text(claude_roles / f"{name}.md", claude_text)
            write_text(codex_roles / f"{name}.toml", codex_text)


def git_tracked(root: Path, pattern: str) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", pattern],
        cwd=root,
        text=True,
        capture_output=True,
        check=False,
    )
    return [
        line for line in result.stdout.splitlines() if line and (root / line).exists()
    ]


def check(root: Path) -> list[str]:
    errors: list[str] = []
    try:
        contract = load_contract(root)
    except Exception as exc:
        return [str(exc)]
    if contract.get("standard_version") != VERSION:
        errors.append(f"contract standard_version must be {VERSION}")
    expected_agents, expected_claude = instruction_output(root, contract)
    if read_text(root / "AGENTS.md") != expected_agents:
        errors.append("AGENTS.md is stale; run agentctl render")
    if read_text(root / "CLAUDE.md") != expected_claude:
        errors.append("CLAUDE.md is stale; run agentctl render")
    expected_copilot = copilot_output(root, contract)
    if (
        expected_copilot is not None
        and read_text(root / ".github/copilot-instructions.md") != expected_copilot
    ):
        errors.append(".github/copilot-instructions.md is stale; run agentctl render")
    spec = contract["instructions"]
    if len(expected_agents.encode()) > int(spec["max_rendered_bytes"]):
        errors.append(f"AGENTS.md exceeds {spec['max_rendered_bytes']} bytes")
    if expected_agents.count("\n") > int(spec["max_rendered_lines"]):
        errors.append(f"AGENTS.md exceeds {spec['max_rendered_lines']} lines")
    canonical = root / contract["skills"]["canonical"]
    if canonical.exists():
        for skill in sorted(p for p in canonical.iterdir() if p.is_dir()):
            skill_file = skill / "SKILL.md"
            if not skill_file.is_file():
                continue
            try:
                fields, _ = parse_frontmatter(read_text(skill_file))
                if fields.get("name") != skill.name:
                    errors.append(
                        f"{skill_file.relative_to(root)} name does not match directory"
                    )
                if not fields.get("description"):
                    errors.append(f"{skill_file.relative_to(root)} has no description")
            except ContractError as exc:
                errors.append(f"{skill_file.relative_to(root)}: {exc}")
    errors.extend(sync_skill_links(root, contract, fix=False))
    roles_root = root / contract["roles"]["canonical"]
    if roles_root.exists():
        for role_dir in sorted(p for p in roles_root.iterdir() if p.is_dir()):
            try:
                name, claude_text, codex_text = role_outputs(role_dir)
                claude_path = (
                    root / contract["roles"]["claude_projection"] / f"{name}.md"
                )
                codex_path = (
                    root / contract["roles"]["codex_projection"] / f"{name}.toml"
                )
                if read_text(claude_path) != claude_text:
                    errors.append(f"Claude role {name} is stale")
                if read_text(codex_path) != codex_text:
                    errors.append(f"Codex role {name} is stale")
            except Exception as exc:
                errors.append(f"role {role_dir.name}: {exc}")
    tracked_local = git_tracked(root, "**/settings.local.json")
    if tracked_local:
        errors.append("tracked local settings: " + ", ".join(tracked_local))
    secret_pattern = re.compile(r"(?:gh[opusr]_[A-Za-z0-9]{20,}|sk-[A-Za-z0-9]{20,})")
    scan_roots = (root / ".agents", root / "AGENTS.md", root / "CLAUDE.md")
    for base in scan_roots:
        if base.is_file():
            files = [base]
        elif base.exists():
            files = [p for p in base.rglob("*") if p.is_file()]
        else:
            files = []
        for path in files:
            try:
                content = read_text(path)
            except UnicodeDecodeError:
                continue
            if secret_pattern.search(content):
                errors.append(f"token-shaped secret in {path.relative_to(root)}")
    return errors


def minimal_core(root: Path) -> str:
    readme = next(
        (
            p.name
            for p in (root / "README.md", root / "README.rst", root / "README")
            if p.exists()
        ),
        None,
    )
    lines = [f"# {root.name} agent guidance", "", "## Repository workflow", ""]
    if readme:
        lines.append(f"- Read `{readme}` before changing unfamiliar areas.")
    lines += [
        "- Derive build, test, lint, and formatting commands from checked-in manifests and CI; do not invent commands.",
        "- Search for the existing source of truth before adding a new helper, constant, schema, registry, or configuration copy.",
        "- Preserve unrelated user changes and keep edits scoped to the requested task.",
        "- Run checks appropriate to the changed area and report any check that could not be run.",
        "- Treat provider-local memory as temporary. Use the `capture-learning` skill for verified knowledge that should persist.",
    ]
    return "\n".join(lines) + "\n"


def import_claude_role(source: Path, roles_root: Path) -> None:
    fields, body = parse_frontmatter(read_text(source))
    name = fields.get("name", source.stem)
    role_dir = roles_root / name
    role_dir.mkdir(parents=True, exist_ok=True)
    tools = [
        item.strip() for item in fields.get("tools", "").split(",") if item.strip()
    ]
    read_only = not any(tool in {"Edit", "Write", "NotebookEdit"} for tool in tools)
    metadata = {
        "name": name,
        "description": fields.get("description", f"Specialized {name} role."),
        "instructions": "instructions.md",
        "claude": {"tools": tools, "model": fields.get("model", "")},
        "codex": {
            "sandbox_mode": "read-only" if read_only else "workspace-write",
            "model_reasoning_effort": "high" if "review" in name else "medium",
        },
    }
    write_text(role_dir / "role.json", json.dumps(metadata, indent=2))
    write_text(role_dir / "instructions.md", body)


def import_codex_role(source: Path, roles_root: Path) -> None:
    data = tomllib.loads(read_text(source))
    name = data.get("name", source.stem)
    role_dir = roles_root / name
    if (role_dir / "role.json").exists():
        return
    metadata = {
        "name": name,
        "description": data.get("description", f"Specialized {name} role."),
        "instructions": "instructions.md",
        "claude": {"tools": [], "model": ""},
        "codex": {
            key: data[key]
            for key in ("model", "model_reasoning_effort", "sandbox_mode")
            if data.get(key)
        },
    }
    write_text(role_dir / "role.json", json.dumps(metadata, indent=2))
    write_text(role_dir / "instructions.md", data.get("developer_instructions", ""))


def migrate_commands(root: Path, commands_dir: str = ".claude/commands") -> None:
    commands = root / commands_dir
    skills = root / ".agents/skills"
    if not commands.exists():
        return
    for source in sorted(commands.rglob("*.md")):
        relative = source.relative_to(commands).with_suffix("")
        name = "-".join(relative.parts).replace(".", "-")
        target = skills / name / "SKILL.md"
        created = False
        if target.exists():
            continue
        text = read_text(source)
        try:
            fields, body = parse_frontmatter(text)
            description = (
                fields.get("description")
                or f"Run the {name} repository workflow when explicitly requested."
            )
        except ContractError:
            body = text
            description = (
                f"Run the {name} repository workflow when explicitly requested."
            )
        write_text(
            target,
            f"---\nname: {name}\ndescription: {description}\n---\n\n{body.strip()}\n",
        )
        created = True
        if created:
            source.unlink()
            source.symlink_to(os.path.relpath(target, source.parent))


def migrate(
    root: Path,
    claude_agents_dir: str | None = None,
    claude_commands_dir: str | None = None,
) -> None:
    agents_root = root / ".agents"
    instructions = agents_root / "instructions"
    instructions.mkdir(parents=True, exist_ok=True)
    contract_path = agents_root / "contract.json"
    if not contract_path.exists():
        write_text(contract_path, json.dumps(DEFAULT_CONTRACT, indent=2))
    core = instructions / "core.md"
    if not core.exists():
        existing_agents = read_text(root / "AGENTS.md")
        existing_claude = read_text(root / "CLAUDE.md")
        if existing_agents and GENERATED not in existing_agents:
            write_text(core, existing_agents)
        elif existing_claude and GENERATED not in existing_claude:
            write_text(core, existing_claude)
        else:
            write_text(core, minimal_core(root))
    for name in ("claude.md", "codex.md"):
        path = instructions / name
        if not path.exists():
            write_text(path, "")
    copilot_source = root / ".github/copilot-instructions.md"
    copilot_delta = instructions / "copilot.md"
    if copilot_source.is_file() and not copilot_delta.exists():
        existing_copilot = read_text(copilot_source)
        if GENERATED not in existing_copilot:
            write_text(copilot_delta, existing_copilot)
    capture = agents_root / "skills/capture-learning/SKILL.md"
    if not capture.exists():
        write_text(capture, CAPTURE_SKILL)
    old_skills = root / ".claude/skills"
    canonical_skills = agents_root / "skills"
    if old_skills.exists() and not old_skills.is_symlink():
        for old in sorted(old_skills.iterdir()):
            if old.is_symlink() or not old.is_dir() or not (old / "SKILL.md").is_file():
                continue
            target = canonical_skills / old.name
            if target.exists():
                if tree_hash(old) != tree_hash(target):
                    raise ContractError(f"skill collision for {old.name}")
                shutil.rmtree(old)
            else:
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(old), str(target))
    migrate_commands(root, claude_commands_dir or ".claude/commands")
    role_sources = root / (claude_agents_dir or ".claude/agents")
    if role_sources.exists():
        for source in sorted(role_sources.glob("*.md")):
            try:
                import_claude_role(source, agents_root / "roles")
            except ContractError:
                continue
    codex_role_sources = root / ".codex/agents"
    if codex_role_sources.exists():
        for source in sorted(codex_role_sources.glob("*.toml")):
            import_codex_role(source, agents_root / "roles")
    destination = agents_root / "agentctl.py"
    if Path(__file__).resolve() != destination.resolve():
        shutil.copy2(Path(__file__), destination)
    workflow = root / ".github/workflows/agent-contract.yml"
    if not workflow.exists():
        write_text(workflow, WORKFLOW)
    render(root)


def install_global(source_root: Path) -> None:
    skills = source_root / "skills"
    if not skills.is_dir():
        raise ContractError(f"missing shared skills directory: {skills}")
    destinations = [Path.home() / ".agents/skills", Path.home() / ".claude/skills"]
    for destination in destinations:
        destination.mkdir(parents=True, exist_ok=True)
        for skill in sorted(
            p for p in skills.iterdir() if p.is_dir() and (p / "SKILL.md").is_file()
        ):
            link = destination / skill.name
            if link.exists() or link.is_symlink():
                if link.resolve() == skill.resolve():
                    continue
                raise ContractError(
                    f"refusing to replace existing global skill: {link}"
                )
            link.symlink_to(skill.resolve(), target_is_directory=True)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="agentctl")
    sub = parser.add_subparsers(dest="command", required=True)
    for name in ("render", "check"):
        command = sub.add_parser(name)
        command.add_argument("root", nargs="?", default=".")
    migrate_command = sub.add_parser("migrate")
    migrate_command.add_argument("root", nargs="?", default=".")
    migrate_command.add_argument("--claude-agents-dir")
    migrate_command.add_argument("--claude-commands-dir")
    install = sub.add_parser("install-global")
    install.add_argument("source_root", nargs="?", default=".")
    args = parser.parse_args(argv)
    try:
        root = Path(getattr(args, "root", ".")).resolve()
        if args.command == "render":
            render(root)
        elif args.command == "check":
            errors = check(root)
            if errors:
                print("Portable Agent Contract: FAIL", file=sys.stderr)
                for error in errors:
                    print(f"- {error}", file=sys.stderr)
                return 1
            print(f"Portable Agent Contract {VERSION}: OK")
        elif args.command == "migrate":
            migrate(root, args.claude_agents_dir, args.claude_commands_dir)
        elif args.command == "install-global":
            install_global(Path(args.source_root).resolve())
        return 0
    except (ContractError, OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"agentctl: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())

# fmt: on
